#cloud-config
package_update: true
package_upgrade: true

# Install packages via apt. To add packages it might be required to add additional sources above.
packages:
 - unzip
 - git
 - wget
 - curl
 - apt-transport-https
 - software-properties-common  

runcmd:
 - curl ${var.jmeter3_url} > jMeter.tgz
 - tar zxvf jMeter.tgz
 #- curl xxxx 
 - my_ip=$(hostname -I)
 - sudo apache-jmeter-3.3/bin/jmeter-server -Dserver.rmi.localport=50000 -Dserver_port=1099 -Djava.rmi.server.hostname=$my_ip -Jserver.rmi.ssl.disable=true 

final_message: "The system is finally up, after $UPTIME seconds"