version: '3'
services:        
  influxdb:                
    image: influxdb:1.7-alpine      
    ports:                        
    - "8086:8086"            
    environment:                        
      - INFLUXDB_DB=jmeter
      - INFLUXDB_GRAPHITE_ENABLED=true
  grafana:                
    build:                        
      context: "grafana"                
    ports:                        
      - "3000:3000"                
    depends_on:                        
      - influxdb                        
